{
 "title": "App Observability Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[30s])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) by (path) / sum(rate(http_request_duration_seconds_count[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Requests by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[30s])) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "App CPU %"
    }
   ]
  }
 ]
}